import './tags/nav-web';
import './tags/foot-web';
import './tags/about-us';
import './tags/hero-intro';
import './tags/hero-jumbotron';
import './tags/hero-interested';
import './card/card-home';
import './card/card-contentarticle';
import './card/card-contentevent';
